### ISSUE TITLE
Upstream list of parsers

### ISSUE THREAD

**Issue by clason** [sogaiu/ts-questions#4]
Thank you for maintaining the list of parser repos! I have combined it with the list of parsers included in nvim-treesitter and put it up on our wiki page: https://github.com/nvim-treesitter/nvim-treesitter/wiki/List-of-parsers (which is meant to eventually replace the "language request" tracking issue).

To avoid duplicate work, I'd suggest keeping that list as the record of truth (and any additions would be welcome)!

**Comment by sogaiu** [comment]
Sounds good.

I'll consider how to adjust things here to reference the nvim-treesitter list you mentioned.

**Comment by clason** [comment]
Let me know if the format should be adjusted to make this easier. (I'm considering removing the markup for the links for better readability anyway.)

**Comment by sogaiu** [comment]
Thanks for the offer.  If it's an issue I'll bug you about it :)

**Comment by sogaiu** [comment]
Scraping went ok and I [updated the list](https://github.com/sogaiu/ts-questions/commit/62634b79918e748e60ef0f7c0af8fef1729ffa96).

If you happen to change the format please let me know (or if there's some issue I should subscribe to, I'm happy to do that instead).  I think there's a good chance adjustments can be made on this end.

If that all seems good, please close the issue at your convenience.

**Comment by clason** [comment]
Will do! And please feel free to add to the list when you come across new parsers (you should be able to edit the Wiki).

**Comment by clason** [comment]
You may also be interested in our latest project: https://github.com/tree-sitter-grammars ;)

**Comment by sogaiu** [comment]
Thanks for the heads up!

I saw that amaanq had mentioned it in passing at the tree-sitter repository and have been interrogating him about it :)
