### ISSUE TITLE
Duplicates in list

### ISSUE THREAD

**Issue by ObserverOfTime** [sogaiu/ts-questions#5]
Repositories that produce multiple parsers are duplicated in the list.
(e.g. tree-sitter-csv produces 3 parsers (csv, tsv, psv) and has 3 entries)
https://github.com/sogaiu/ts-questions/blob/93b9e7799d55dc0cd7d5600475891d971da2d8a5/ts-grammar-repositories.txt#L117-L119

**Comment by sogaiu** [comment]
Thanks.  Looks like there may be some other duplicates as well.

It's possible these got picked up when scraping [nvim-treesitter's list](https://github.com/sogaiu/ts-questions/issues/4).  I should deduplicate (^^;

**Comment by sogaiu** [comment]
I made an attempt [here](https://github.com/sogaiu/ts-questions/commit/e0213bed4f7eb202385a704dcc5dcb7f5a87dfa4).

If that looks good to you, please close this issue.

**Comment by sogaiu** [comment]
Ok, some of the duplication is due to content like this:

```
- [X] [csv](https://github.com/amaanq/tree-sitter-csv)
```

```
- [X] [psv](https://github.com/amaanq/tree-sitter-csv)
```

I guess I'll change the scraper to just keep one of these sorts of things.

_Update_: scraper has been modified.
